# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Summit Integration Test

on:
  repository_dispatch:
    types: [ opened, deleted ]

jobs:
  inter_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Check event
        run: |
          echo 'Hello'
          echo ${{github.event.event_type}}
          echo "Event text: ${{ github.event.client_payload.text }}"
          echo 0
