name: Summit Integration Test

on:
  repository_dispatch:
    types: [ test_result ]

jobs:
  inter_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Check event
        run: |
          echo "Event text: ${{ github.event.client_payload.text }}"
          if [ "$MYAPP_ENV" == "PROD" ]
          then
              echo "Success"
              echo 0
          else
              echo "Failure"
              echo 1
          fi